source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
use_frameworks!

target 'Woo_v2' do
    pod 'Firebase/DynamicLinks'
    pod 'Masonry'
    pod 'IQKeyboardManager'
    pod 'UAProgressView'
    pod 'SVSegmentedControl'
    pod 'JazzHands'
    #pod 'MaterialControls', '~> 1.0.2'
    pod 'FBSDKCoreKit','5.8.0'
    pod 'FBSDKLoginKit','5.8.0'
    pod 'AccountKit', '5.0.1'
    pod 'GoogleConversionTracking'
    pod 'GoogleAnalytics'
    pod 'AppsFlyerFramework','4.11.0'
    #pod 'AppsFlyer-SDK'
    #pod 'DACircularProgress'
    pod 'Alamofire','4.9.0'
    pod 'LDProgressView’
    pod 'NMRangeSlider'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Crashlytics'
#    pod 'LayerKit','4.0.2'
    #pod 'Koloda'
    pod 'SnapKit'
    pod 'MMDrawerController','0.5.7'
    pod 'pop', '1.0.9'
    pod 'Firebase'
    
#    cropper library added by akarsh
    pod 'CropPickerController'
    
#    pods add by Akarsh for firebase phone authentication
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Phone'
    pod 'Firebase/Auth'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
#    pod 'Firebase/Crash'
    pod 'Mixpanel','3.5.0'
    pod 'VerticalSlider'
    pod 'SDWebImage','4.4.2'
    pod 'SDWebImage/GIF'
    pod 'PINRemoteImage'
    #pod 'LytroKit'
    pod 'TrueSDK'
    pod 'Applozic', '~> 6.12.0'
    pod 'SwipeBack', '~> 1.1'
    pod 'AgoraRtm_iOS'
    pod 'GooglePlaces'
end

target 'Woo_v2Tests' do
    
end

post_install do |installer|
 `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end

#$(PROJECT_DIR)/Pods/FirebaseCrash/Frameworks
